name: Linter

on: push

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Run linter
        run:
          make install
          make lint
        env:
          DEFAULT_BRANCH: main